app:
    name: backend-serivce
    port: "8080"
log:
    env: "dev"
database:
    username: root
    password: root
    host: 127.0.0.1
    port: 3306
    dbname: payment
gateway:
    productservice:
        hosturl: "http://127.0.0.1:8081"