app:
    name: backend-serivce
    port: "8080"
log:
    env: "dev"
database:
    username: user
    password: password
    host: 127.0.0.1
    port: 5432
    dbname: main
gateway:
    productservice:
        hosturl: "http://127.0.0.1:8081"